version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - task-storage:/data

  db:
    image: postgres:13-alpine
    container_name: postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  task-storage: null
  db-data: null