name: CI/CD_DEV

on:
  push:
    branches-ignore:
      - master
      - release/**

jobs:
  linter:
    name: Check linter
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout the latest code
        uses: actions/checkout@v2
      - name: Install black
        run: pip install black
      - name: Checking...
        run: black --check .

  bandit:
    name: Bandit
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - uses: actions/checkout@v1
      - name: Install bandit
        run: pip install bandit
      - name: Run bandit
        run: bandit -r --exclude head/management/commands, head/head/

  flake8:
    name: Flake8
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - uses: actions/checkout@v1
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  test:
    name: Test
    needs: [flake8, bandit, linter]
    runs-on: ubuntu-22.04
    services:
      postgresql:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./base_requirements.txt
          pip install -r ./tests_requirements.txt
      - name: Run tests
        run: pytest --exitfirst